# Default initial positions for stretch's ros2_control fake system

initial_positions:
  joint_arm_l0: 0
  joint_arm_l1: 0
  joint_arm_l2: 0
  joint_arm_l3: 0
  joint_lift: 0
  joint_wrist_pitch: 0
  joint_wrist_roll: 0
  joint_wrist_yaw: 0
  position: 0