mobile_base_arm:
  kinematics_solver: stretch_kinematics_plugin/StretchKinematicsPlugin
  kinematics_solver_search_resolution: 0.0050000000000000001
  kinematics_solver_timeout: 3.50000000000000003

# mobile_base_arm:
#   kinematics_solver: pick_ik/PickIkPlugin
#   kinematics_solver_timeout: 0.05
#   kinematics_solver_attempts: 3
#   mode: global
#   position_scale: 1.0
#   rotation_scale: 0.5
#   position_threshold: 0.001
#   orientation_threshold: 0.01
#   cost_threshold: 0.001
#   minimal_displacement_weight: 0.0
#   gd_step_size: 0.0001


stretch_arm:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.0050000000000000001
  kinematics_solver_timeout: 0.50000000000000003
  kinematics_solver_attempts: 5

  # This will solve it, but I dought it would work well
  # position_only_ik: True


# stretch_arm:
#   kinematics_solver: pick_ik/PickIkPlugin
#   kinematics_solver_timeout: 0.05
#   kinematics_solver_attempts: 3
#   mode: global
#   position_scale: 1.0
#   rotation_scale: 0.5
#   position_threshold: 0.001
#   orientation_threshold: 0.01
#   cost_threshold: 0.001
#   minimal_displacement_weight: 0.0
#   gd_step_size: 0.0001
