# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    stretch_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    position_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    mobile_base_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


stretch_controller:
  ros__parameters:
    joints:
      - position
      - joint_lift
      - joint_arm_l3
      - joint_arm_l2
      - joint_arm_l1
      - joint_arm_l0
      - joint_wrist_yaw
      - joint_wrist_pitch
      - joint_wrist_roll
      - joint_head_pan
      - joint_head_tilt
      - joint_gripper_finger_left
      - joint_gripper_finger_right
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity