# The name of this file shouldn't be changed, or else the Setup Assistant won't detect it
sensors:
- head_cloud
head_cloud:
    sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    # stretch_core/launch/d435i_high_resolution.launch.py publishes: 
    # /camera/depth/color/points [sensor_msgs/msg/PointCloud2]
    point_cloud_topic: /camera/depth/color/points
    max_range: 2.0
    max_update_rate: 1.0
    padding_offset: 0.05 # filter boundary (in cm)
    padding_scale: 1.0
    point_subsample: 5
    filtered_cloud_topic: /camera/depth/color/filtered_points
# head_cloud:
#     sensor_plugin: occupancy_map_monitor/DepthImageOctomapUpdater
#     image_topic: /camera/depth/image_rect_raw
#     queue_size: 1
#     near_clipping_plane_distance: 0.1
#     far_clipping_plane_distance: 2.0
#     shadow_threshold: 0.2
#     padding_scale: 1.0
#     padding_offset: 0.05
#     max_update_rate: 1.0
#     filtered_cloud_topic: /camera/depth/color/filtered_points
octomap_resolution: 0.01
